# version: '3.8'

# services:
#   postgres:
#     container_name: caas
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=postgres

version: '3'
services:
  inventory-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "PgAdminInventory"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
  inventory-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "james@w3.care"
      PGADMIN_DEFAULT_PASSWORD: "PgAdminInventory!"
    ports:
      - "16543:80"
    depends_on:
      - inventory-compose
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge